# Generated by Django 3.0 on 2021-03-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssueCrime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_title', models.CharField(max_length=255)),
                ('crime_description', models.TextField()),
                ('crime_location', models.CharField(default='Jigawa', max_length=255)),
                ('lga', models.CharField(choices=[('dutse', 'DUTSE'), ('bkd', 'BIRNINKUDU'), ('hadejia', 'HADEJIA'), ('ringim', 'RINGIM'), ('gumel', 'GUMEL'), ('kazaure', 'KAZAURE')], default='dutse', max_length=32)),
                ('street_address', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=50)),
            ],
        ),
    ]
