# Generated by Django 3.0 on 2021-05-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuecrime',
            name='treated',
            field=models.BooleanField(default=False),
        ),
    ]
